# Common config
services:
  client:
    build:
      context: client/
  django:
    restart: unless-stopped
    build:
      context: django/
    depends_on:
      - db
    networks:
      - main
  db:
    image: postgres:14.1-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - main
  nginx:
    restart: unless-stopped
    build:
      context: nginx/
    depends_on:
      - client
    env_file:
      - .env
    networks:
      - main
    ports:
      - 80:80
      - 443:443
    volumes:
      - static:/static:ro
      - acmechallenge:/var/www/certbot:ro
      - letsencrypt:/etc/letsencrypt:ro
  # certbot:
  #   image: certbot/certbot
  #   depends_on:
  #     - nginx
  #   volumes:
  #     - acmechallenge:/var/www/certbot
  #     - letsencrypt:/etc/letsencrypt
  #   command: certonly --register-unsafely-without-email --agree-tos --webroot -w /var/www/certbot/ -d soodud.ee
  #   # command: certonly -d soodud.ee --dry-run
  #   # command: renew

volumes:
  static:
    external: false
  acmechallenge:
    external: false
  letsencrypt:
    external: false

networks:
  main:
    driver: bridge
