# Generated by Django 4.0.3 on 2022-03-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_alter_storeproduct_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='start',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
