# Generated by Django 4.0.3 on 2022-03-21 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_alter_price_base_price_alter_price_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='base_price',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='sale_price',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
