# Generated by Django 4.0.3 on 2022-03-21 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_alter_product_image_url_alter_product_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='current',
        ),
        migrations.AddField(
            model_name='storeproduct',
            name='current_price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.price'),
        ),
    ]
