# Generated by Django 4.0.3 on 2022-03-22 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_remove_price_current_storeproduct_current_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeproduct',
            name='hash',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
