# Generated by Django 4.0.3 on 2022-03-22 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_storeproduct_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='end',
        ),
        migrations.AddField(
            model_name='storeproduct',
            name='has_barcode',
            field=models.BooleanField(default=False),
        ),
    ]
