# Generated by Django 4.0.3 on 2022-03-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_storeproduct_certainty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
