# Generated by Django 4.0.3 on 2022-04-17 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_alter_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='base_price',
            field=models.FloatField(blank=True, default=None),
        ),
    ]
