# Generated by Django 4.0.3 on 2022-04-20 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_alter_price_base_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
        migrations.AlterField(
            model_name='storeproduct',
            name='hash',
            field=models.CharField(max_length=100),
        ),
    ]
